### ISSUE TITLE
About: Catch statement does not catch thrown error

### ISSUE THREAD

**Issue by mozgbrasil** [Ilshidur/can-iframe-url#2]
Good afternoon my friends

I'm using your extension

But one of the URLs is being thrown error even using `try / catch`, as I do to suppress the error

Catch statement does not catch thrown error

Can you help me please

-

    var url = 'https://www.w3schools.com/js/js_errors.asp'; // Ok
    var url = 'http://objetosdeaprendizagem.com.br/como-a-historia-da-taxonomia-de-bloom-pode-me-ajudar-a-ensinar-melhor/'; // Z_BUF_ERROR

    // console.log('url: ', url);

    var includeAllowed = "failed";

    try {
      var includeAllowed = await canIframeUrl(url);
    } catch (err) {
      console.log("🔴️ err.message: ");
    } finally {
      console.log("🔷️ try.finally");
    }

    console.log('includeAllowed: ', includeAllowed);

-

![Captura de tela de 2019-10-29 18-09-38](https://user-images.githubusercontent.com/17202780/67809345-4fe57200-fa77-11e9-8ba3-a1ebc42a6b44.png)

**Comment by Ilshidur** [comment]
Hello.

I just tried it on [RunKit](https://npm.runkit.com/can-iframe-url) and I can't reproduce this.

Also, `await canIframeUrl('http://objetosdeaprendizagem.com.br/como-a-historia-da-taxonomia-de-bloom-pode-me-ajudar-a-ensinar-melhor/')` doesn't throw on my end and returns `true`.

Can you elaborate please ?

**Comment by mozgbrasil** [comment]
Good Morning

I just did the recommended test and the occurrence really has nothing to do with the extension

I'm sorry for anything
